-- 코드를 입력하세요
SELECT 
YEAR(SALES_DATE) AS YEAR, 
MONTH(SALES_DATE) AS MONTH, 
GENDER, 
COUNT(DISTINCT ONLINE_SALE.USER_ID) AS USERS
FROM USER_INFO 
INNER JOIN ONLINE_SALE ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY 1,2,3
ORDER BY 1,2,3;